changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: ✨ New Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: ⚡️ Performance Improvements
      labels:
        - performance
    - title: 🛠️ Refactors
      labels:
        - refactor
    - title: 📚 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
        - "!feature"
        - "!bug"